# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-02 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('qualification', models.CharField(max_length=255)),
                ('slug', models.SlugField(null=True)),
                ('projects', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, default='N/A', max_length=500)),
                ('pic', models.ImageField(blank=True, max_length=255, null=True, upload_to='profile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_fields', models.CharField(max_length=255)),
                ('experience_years', models.IntegerField()),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Project_em',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('project_description', models.FileField(upload_to='projects')),
                ('project_begin', models.DateField()),
            ],
        ),
    ]
