# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-04 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='experience',
            table='experience',
        ),
    ]
