# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-04 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20190704_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project_em',
        ),
    ]
