# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-04 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_delete_project_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('project_description', models.FileField(upload_to='projects')),
                ('project_begin', models.DateField()),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='employees.Employee')),
            ],
            options={
                'db_table': 'employees_projects',
            },
        ),
    ]
