# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-05 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20190802_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='git',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
