# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-04 11:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_description',
            field=models.FileField(upload_to='projects', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
