# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-08 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20190705_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pic',
            field=models.ImageField(blank=True, default='profile/default.png', max_length=255, null=True, upload_to='profile'),
        ),
    ]
