# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-17 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_by',
            new_name='employee_id',
        ),
    ]
