# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-18 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20190717_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
