# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-18 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_auto_20190718_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(to='employees.Projects'),
        ),
    ]
