# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-21 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='projects',
        ),
    ]
