# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-22 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_auto_20190721_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='employee_id',
        ),
    ]
