# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-22 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_projects_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='employees.Employee'),
        ),
    ]
