# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-23 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_auto_20190722_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='employees.Employee'),
        ),
    ]
