# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-23 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_auto_20190723_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='employee_id',
        ),
    ]
